### ISSUE TITLE
Attached to player

### ISSUE THREAD

**Issue by MolotovUnstable** [MennoMax/astikor-carts#23] opened 2019-02-25 06:35 UTC
Free carts become attached to the player after restart
![2019-02-25_09 32 52](https://user-images.githubusercontent.com/47965558/53318508-8bc0aa00-38e0-11e9-929c-7ceedbdff047.png)
![2019-02-25_09 33 28](https://user-images.githubusercontent.com/47965558/53318513-91b68b00-38e0-11e9-9246-278a4915c42c.png)

**Comment by MennoMax** [comment] 2019-02-25 16:41
I am unable to reproduce this issue.

Are there any other steps required other than having a unattached cart nearby?
Which version of this mod are you playing on?

**Comment by MennoMax** [comment] 2019-10-02 19:14
Closing since nobody else seems to be able to reproduce this issue.

**Closed by MennoMax** 2019-10-02 19:14 UTC
Labels: unconfirmed
