### ISSUE TITLE
 Add support for Public GUI Announcement mod

### ISSUE THREAD

**Issue by SepSol** [MennoMax/astikor-carts#40] opened 2019-10-23 12:04 UTC
When using different Cart menus, no GUI shows up. Please add support for [PGA](https://www.curseforge.com/minecraft/mc-mods/public-gui-announcement) mod. Thanks.

**Comment by MennoMax** [comment] 2019-10-23 12:07
You already opened an issue related to this, even answered to my response.

Duplicate of #38

**Closed by MennoMax** 2019-10-23 12:07 UTC

**Comment by SepSol** [comment] 2019-10-23 12:09
Sorry, I'm adding issues all over the place these days! sometimes I forget :)
